#!/usr/bin/env python3
"""Build or check verbatim Markdown packs; standard library only, no runtime use."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADING = re.compile(r"^## (\d+)\. [^\n]+", re.MULTILINE)


def load_rules(root: Path) -> dict[int, str]:
    """Read each numbered canonical rule exactly once and validate its contract."""
    files = sorted((root / "references").glob("*.md"))
    if len(files) != 5:
        raise ValueError("references/ must contain exactly five numbered Markdown files")
    rules: dict[int, str] = {}
    starts = []
    for path in files:
        prefix = re.match(r"^(\d{2})-[a-z-]+\.md$", path.name)
        if not prefix:
            raise ValueError(f"Unnumbered reference: {path.name}")
        text = path.read_text(encoding="utf-8")
        matches = list(HEADING.finditer(text))
        ids = [int(m.group(1)) for m in matches]
        if not ids or ids[0] != int(prefix.group(1)):
            raise ValueError(f"Filename prefix must equal first rule: {path.name}")
        if ids != list(range(ids[0], ids[-1] + 1)):
            raise ValueError(f"Non-contiguous rule IDs: {path.name}")
        starts.append(ids[0])
        for i, match in enumerate(matches):
            number = ids[i]
            if number in rules:
                raise ValueError(f"Duplicate canonical rule: {number}")
            end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
            block = text[match.start():end].strip()
            if block.count("**Requirement:**") != 1 or block.count("**Pass:**") != 1:
                raise ValueError(f"Rule {number} needs one Requirement and one Pass")
            rules[number] = block
    if starts != [1, 11, 24, 40, 51] or set(rules) != set(range(1, 56)):
        raise ValueError("Expected reference starts 01/11/24/40/51 and rule IDs 1–55")
    return rules


def load_packs(root: Path, rules: dict[int, str]) -> list[tuple[str, dict, set[int]]]:
    """Resolve cumulative membership and reject gaps, cycles, and dangling rules."""
    config = json.loads((root / "packs.json").read_text(encoding="utf-8"))
    if set(config) != {"core", "polish", "full"}:
        raise ValueError("packs.json must define core, polish, and full")
    resolved: dict[str, set[int]] = {}

    def resolve(name: str, trail: tuple[str, ...] = ()) -> set[int]:
        if name in trail or name not in config:
            raise ValueError(f"Invalid pack inheritance: {' -> '.join((*trail, name))}")
        if name in resolved:
            return resolved[name]
        spec = config[name]
        raw = spec["rules"]
        if raw == "all":
            ids = set(rules)
        elif isinstance(raw, list) and all(type(n) is int for n in raw):
            ids = set(raw)
            if len(ids) != len(raw) or not ids <= rules.keys():
                raise ValueError(f"Duplicate or unknown rule in pack {name}")
        else:
            raise ValueError(f"Invalid rules for pack {name}")
        if "extends" in spec:
            inherited = resolve(spec["extends"], (*trail, name))
            if ids & inherited:
                raise ValueError(f"Pack {name} repeats inherited rule membership")
            ids = ids | inherited
        resolved[name] = ids
        return ids

    result = []
    for level, name in enumerate(("core", "polish", "full"), 1):
        spec = config[name]
        filename = f"{level:02d}-{name}.md"
        if spec["level"] != level or spec["file"] != filename:
            raise ValueError(f"Pack {name} must use level {level} and file {filename}")
        ids = resolve(name)
        for number in ids:
            dependencies = {int(n) for n in re.findall(r"\bRule (\d+)\b", rules[number])}
            missing = dependencies - ids
            if missing:
                raise ValueError(f"Pack {name}, rule {number}: missing dependencies {sorted(missing)}")
        result.append((name, spec, ids))
    if not resolved["core"] < resolved["polish"] < resolved["full"] == set(rules):
        raise ValueError("Expected strictly cumulative Core < Polish < Full = 1–55")
    if 2 not in resolved["core"]:
        raise ValueError("Rule 2 is required in every pack")
    return result


def expected_packs(root: Path) -> dict[str, str]:
    rules = load_rules(root)
    outputs = {}
    for name, spec, ids in load_packs(root, rules):
        header = (
            f"# Pack {spec['level']} — {name.title()}\n\n"
            "<!-- Generated by scripts/build_packs.py. Edit references/ or packs.json, not this file. -->\n\n"
            f"**Scope:** {len(ids)} mandatory requirements. Enforce each present target; "
            "use the SKILL.md evidence lock and genre boundaries.\n\n"
            "**Rule IDs:** " + ", ".join(str(n) for n in sorted(ids)) + ".\n\n"
            "This file contains the complete selected rule blocks. No additional reference "
            "reads are required.\n\n"
        )
        outputs[spec["file"]] = header + "\n\n".join(rules[n] for n in sorted(ids)) + "\n"
    return outputs


def build(root: Path, check: bool = False) -> dict[str, str]:
    outputs = expected_packs(root)
    directory = root / "packs"
    extras = {p.name for p in directory.glob("*.md")} - outputs.keys()
    if extras:
        raise ValueError(f"Stale pack files must be removed: {sorted(extras)}")
    stale = [name for name, text in outputs.items()
             if not (directory / name).exists()
             or (directory / name).read_text(encoding="utf-8") != text]
    if check and stale:
        raise ValueError(f"Regenerate packs with scripts/build_packs.py: {', '.join(stale)}")
    if not check:
        directory.mkdir(exist_ok=True)
        for name, text in outputs.items():
            (directory / name).write_text(text, encoding="utf-8")
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check freshness without writing")
    args = parser.parse_args()
    try:
        outputs = build(ROOT, check=args.check)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print(f"{'Checked' if args.check else 'Built'} {len(outputs)} packs from 55 canonical rules.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
