repos:
  - repo: https://github.com/ysawa0/precommit
    rev: "1.5"
    hooks:
      - id: oxfmt
      - id: ruff-check
      - id: ruff-format
      - id: unbold
      - id: shellcheck
      - id: shfmt
