repos:
  - repo: https://github.com/ysawa0/precommit
    rev: "1.7"
    hooks:
      - id: oxfmt
      - id: oxlint
      - id: ruff-check
      - id: ruff-format
      - id: unbold
      - id: shellcheck
      - id: shfmt
