repos:
  - repo: https://github.com/ysawa0/precommit
    rev: "1.10"
    hooks:
      - id: oxfmt
      - id: oxlint
      - id: ruff-format
      - id: ruff-check
      - id: unbold
      - id: goimports
      - id: gofumpt
      - id: gopls-check
      - id: go-vet
      - id: shfmt
      - id: shellcheck
