line-length = 300

[lint]
select = ["ALL"]
# Skip boilerplate requirements and leave formatting to ruff-format.
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
  "D", "DOC", "CPY001", "T201", "EM", "TRY003",
  "TID252", "INP001", "PT009", "PT027",
  "COM812", "COM819",
  "E111", "E114", "E117", "ISC002",
  "Q000", "Q001", "Q002", "Q003", "Q004", "W191",
]

[lint.pylint]
max-nested-blocks = 2

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
